# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import keyvaluestore_pb2 as keyvaluestore__pb2


class KeyValueStoreStub(object):
    """A simple key-value storage service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetValue = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/GetValue',
                request_serializer=keyvaluestore__pb2.GetRequest.SerializeToString,
                response_deserializer=keyvaluestore__pb2.Response.FromString,
                )
        self.PutValue = channel.unary_unary(
                '/keyvaluestore.KeyValueStore/PutValue',
                request_serializer=keyvaluestore__pb2.PutRequest.SerializeToString,
                response_deserializer=keyvaluestore__pb2.Response.FromString,
                )


class KeyValueStoreServicer(object):
    """A simple key-value storage service
    """

    def GetValue(self, request, context):
        """Provides a value for each get request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutValue(self, request, context):
        """Returns the old value (default null) for each put request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=keyvaluestore__pb2.GetRequest.FromString,
                    response_serializer=keyvaluestore__pb2.Response.SerializeToString,
            ),
            'PutValue': grpc.unary_unary_rpc_method_handler(
                    servicer.PutValue,
                    request_deserializer=keyvaluestore__pb2.PutRequest.FromString,
                    response_serializer=keyvaluestore__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyvaluestore.KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """A simple key-value storage service
    """

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/GetValue',
            keyvaluestore__pb2.GetRequest.SerializeToString,
            keyvaluestore__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/keyvaluestore.KeyValueStore/PutValue',
            keyvaluestore__pb2.PutRequest.SerializeToString,
            keyvaluestore__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
